name: TPClash4Android Release

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - release

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Put back the git branch into git
      shell: bash
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Get the latest version info of TPClash
      id: latest
      shell: bash
      run: |
        echo "latest=$(curl -sSL https://api.github.com/repos/TPClash/TPClash/releases/latest | \
            jq -r '.assets[].browser_download_url | select (. | test("tpclash-mihomo-android-arm64"))')" >> $GITHUB_OUTPUT
    - name: Download the latest version of TPClash
      shell: bash
      run: |
        mkdir tpclash/bin/
        curl -sSL ${{ steps.latest.outputs.latest }} > tpclash/bin/tpclash-mihomo-android-arm64
        chmod +x tpclash/bin/tpclash-mihomo-android-arm64
    - name: Get current date
      id: timestamp
      run: |
        export TZ='Asia/Shanghai'
        echo "date=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
    - name: Extract Tag Name
      id: extract_tag
      run: |
        echo "tag_name=$(echo $GITHUB_REF | awk -F/ '{print $3}')" >> $GITHUB_OUTPUT
    - name: Zip the files
      shell: bash
      run: |
        zip -q -r TPClash4Android-${{ steps.extract_tag.outputs.tag_name }}.zip *
    - name: Generate release info
      id: info
      run: |
          echo "${{ steps.extract_tag.outputs.tag_name }}" >> release.txt
          echo "" >> release.txt
          echo "${{ secrets.RELEASE_INFO }}" >> release.txt
          echo "" >> release.txt
          echo "Build time: ${{ steps.timestamp.outputs.date }}" >> release.txt
          echo "Telegram: https://t.me/tpclash" >> release.txt
          touch release.txt
    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.G1THUB_TOKEN }}
      with:
          prerelease: ${{ secrets.PRERELEASE }}
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          body_path: release.txt
          files: ./TPClash4Android-${{ steps.extract_tag.outputs.tag_name }}.zip
